# Use the official Node.js image with a specified version
FROM node:18

# Set the working directory inside the container
WORKDIR /usr/src/app

# Add `/usr/src/app/node_modules/.bin` to the $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port on which the app runs (if necessary, adjust based on your application's needs)
EXPOSE 3000

# Start the application
# CMD ["npm", "run", "start"]

CMD ["npm", "run", "dev"]

# para corr 