# FROM node:20.5.1

FROM node:18

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install 

COPY . .

EXPOSE 3000

RUN npm audit fix

CMD ["npm", "run", "dev"]

# para corr 